'use client';

import { useEffect, useState } from 'react';
import type { SurfReport } from '@/types/surf-report';

interface SurfReportCardProps {
  report: SurfReport | null;
  loading: boolean;
  timezone?: string;
}

// Only surfaces when something is degraded — a report generated normally stays
// visually silent, so the badge reads as a genuine heads-up rather than routine chrome.
function getProvenanceNotice(report: SurfReport | null): string | null {
  if (!report) return null;
  if (report._fallback) {
    return 'Showing an earlier report — the latest update failed';
  }
  const backend = report.generation_meta?.backend;
  if (backend === 'bun-fallback' || backend === 'vercel-local-fallback') {
    return 'Template report — live AI generation was unavailable';
  }
  if (backend === 'openai-secondary') {
    return 'Generated by backup AI model';
  }
  return null;
}

export function SurfReportCard({ report, loading, timezone }: SurfReportCardProps) {
  const [formattedTime, setFormattedTime] = useState<string | null>(null);

  useEffect(() => {
    if (!report?.timestamp) return;
    const reportTime = new Date(report.timestamp);
    const now = new Date();
    const dayKeyOpts: Intl.DateTimeFormatOptions = timezone
      ? { timeZone: timezone, year: 'numeric', month: 'numeric', day: 'numeric' }
      : { year: 'numeric', month: 'numeric', day: 'numeric' };
    const isToday =
      reportTime.toLocaleDateString('en-US', dayKeyOpts) === now.toLocaleDateString('en-US', dayKeyOpts);
    const datePart = isToday
      ? 'Today'
      : reportTime.toLocaleDateString('en-US', { ...dayKeyOpts, month: 'short' });
    const timePart = reportTime.toLocaleTimeString('en-US', {
      ...(timezone ? { timeZone: timezone } : {}),
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    });
    setFormattedTime(datePart + ' @ ' + timePart);
  }, [report?.timestamp, timezone]);

  // Don't render anything if loading and no report
  if (loading && !report) {
    return (
<>
        <div className="h-4"></div>
          <div className="mb-12">
            <div className="h-6 bg-gray-200 rounded w-1/3 block mx-auto"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="h-4"></div>
          <div className="my-8"></div>
            <div className="h-6 bg-gray-200 rounded w-full"></div>
            <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
          <div className="my-8">
            <div className="h-6 bg-gray-200 rounded w-full"></div>
          </div>
 </>
    );
  }

  // Don't render if no report and not loading
  if (!report && !loading) {
    return null;
  }

  const provenanceNotice = getProvenanceNotice(report);

  return (

        <div className="prose prose-lg mb-6">
            <pre className="text-center pt-4 pb-2 uppercase text-gray-500 tracking-wide">{formattedTime ?? ''}</pre>
            {provenanceNotice && (
              <p className="text-center pb-6 text-xs uppercase tracking-wide text-amber-600">
                {provenanceNotice}
              </p>
            )}
            {!provenanceNotice && <div className="pb-8" />}
          <p className="text-gray-800 leading-relaxed text-2xl md:text-3xl whitespace-pre-wrap">
            {report?.report || 'Loading surf report...'}
          </p>
        </div>


  );
}